import 'dart:convert';

/// Data model for a single body-blog entry.
///
/// Each entry represents one day's AI-generated narrative, written from
/// the perspective of the user's body based on real health, environment,
/// and calendar data.
class BodyBlogEntry {
  final DateTime date;
  final String headline;
  final String summary;
  final String fullBody;
  final String mood; // e.g. "calm", "energised", "tired", "restless"
  final String moodEmoji;
  final List<String> tags;
  final BodySnapshot snapshot;

  /// Optional free-text note added manually by the user.
  final String? userNote;

  /// Optional user-reported mood emoji (e.g. '😊', '😔').
  final String? userMood;

  /// Whether this entry's narrative was generated by the AI service.
  /// Persisted so the ✦ AI badge survives app restarts.
  final bool aiGenerated;

  const BodyBlogEntry({
    required this.date,
    required this.headline,
    required this.summary,
    required this.fullBody,
    required this.mood,
    required this.moodEmoji,
    required this.tags,
    required this.snapshot,
    this.userNote,
    this.userMood,
    this.aiGenerated = false,
  });

  BodyBlogEntry copyWith({
    DateTime? date,
    String? headline,
    String? summary,
    String? fullBody,
    String? mood,
    String? moodEmoji,
    List<String>? tags,
    BodySnapshot? snapshot,
    String? userNote,
    bool clearUserNote = false,
    String? userMood,
    bool clearUserMood = false,
    bool? aiGenerated,
  }) {
    return BodyBlogEntry(
      date: date ?? this.date,
      headline: headline ?? this.headline,
      summary: summary ?? this.summary,
      fullBody: fullBody ?? this.fullBody,
      mood: mood ?? this.mood,
      moodEmoji: moodEmoji ?? this.moodEmoji,
      tags: tags ?? this.tags,
      snapshot: snapshot ?? this.snapshot,
      userNote: clearUserNote ? null : (userNote ?? this.userNote),
      userMood: clearUserMood ? null : (userMood ?? this.userMood),
      aiGenerated: aiGenerated ?? this.aiGenerated,
    );
  }

  Map<String, dynamic> toJson() => {
    'date': date.toIso8601String(),
    'headline': headline,
    'summary': summary,
    'full_body': fullBody,
    'mood': mood,
    'mood_emoji': moodEmoji,
    'tags': jsonEncode(tags),
    'user_note': userNote,
    'user_mood': userMood,
    'snapshot': jsonEncode(snapshot.toJson()),
    'ai_generated': aiGenerated ? 1 : 0,
  };

  factory BodyBlogEntry.fromJson(Map<String, dynamic> json) {
    final tagsRaw = json['tags'] as String?;
    final snapshotRaw = json['snapshot'] as String?;
    return BodyBlogEntry(
      date: DateTime.parse(json['date'] as String),
      headline: json['headline'] as String,
      summary: json['summary'] as String,
      fullBody: json['full_body'] as String,
      mood: json['mood'] as String,
      moodEmoji: json['mood_emoji'] as String,
      tags: tagsRaw != null
          ? (jsonDecode(tagsRaw) as List).cast<String>()
          : const [],
      userNote: json['user_note'] as String?,
      userMood: json['user_mood'] as String?,
      aiGenerated: (json['ai_generated'] as int?) == 1,
      snapshot: snapshotRaw != null
          ? BodySnapshot.fromJson(
              jsonDecode(snapshotRaw) as Map<String, dynamic>,
            )
          : const BodySnapshot(),
    );
  }
}

/// Raw data snapshot collected for a given day.
class BodySnapshot {
  final int steps;
  final double caloriesBurned;
  final double distanceKm;
  final double sleepHours;
  final int avgHeartRate;
  final int workouts;
  final double? temperatureC;
  final int? aqiUs;
  final double? uvIndex;
  final String? weatherDesc;
  final String? city;
  final List<String> calendarEvents;

  const BodySnapshot({
    this.steps = 0,
    this.caloriesBurned = 0,
    this.distanceKm = 0,
    this.sleepHours = 0,
    this.avgHeartRate = 0,
    this.workouts = 0,
    this.temperatureC,
    this.aqiUs,
    this.uvIndex,
    this.weatherDesc,
    this.city,
    this.calendarEvents = const [],
  });

  Map<String, dynamic> toJson() => {
    'steps': steps,
    'calories_burned': caloriesBurned,
    'distance_km': distanceKm,
    'sleep_hours': sleepHours,
    'avg_heart_rate': avgHeartRate,
    'workouts': workouts,
    'temperature_c': temperatureC,
    'aqi_us': aqiUs,
    'uv_index': uvIndex,
    'weather_desc': weatherDesc,
    'city': city,
    'calendar_events': jsonEncode(calendarEvents),
  };

  factory BodySnapshot.fromJson(Map<String, dynamic> json) {
    final eventsRaw = json['calendar_events'] as String?;
    return BodySnapshot(
      steps: (json['steps'] as num?)?.toInt() ?? 0,
      caloriesBurned: (json['calories_burned'] as num?)?.toDouble() ?? 0,
      distanceKm: (json['distance_km'] as num?)?.toDouble() ?? 0,
      sleepHours: (json['sleep_hours'] as num?)?.toDouble() ?? 0,
      avgHeartRate: (json['avg_heart_rate'] as num?)?.toInt() ?? 0,
      workouts: (json['workouts'] as num?)?.toInt() ?? 0,
      temperatureC: (json['temperature_c'] as num?)?.toDouble(),
      aqiUs: (json['aqi_us'] as num?)?.toInt(),
      uvIndex: (json['uv_index'] as num?)?.toDouble(),
      weatherDesc: json['weather_desc'] as String?,
      city: json['city'] as String?,
      calendarEvents: eventsRaw != null
          ? (jsonDecode(eventsRaw) as List).cast<String>()
          : const [],
    );
  }
}
